---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: kubectl test
    shell: kubectl apply -f kubernetes/front-end-service-deployment.yaml