apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 8000
      nodePort: 30080
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
