

[Global]
   debug = true

# Tracing definition
[tracing]
  backend = "jaeger"
  serviceName = "traefik"

  [tracing.jaeger]
    samplingServerURL = "http://jaeger:5778/sampling"
    localAgentHostPort = "jaeger:6831"