apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-manager-service-config
  namespace: default
data:
  pfe_tika_host: tika
  pfe_rabbitmq_host: rabbitmq
  pfe_livy_host: hadoop-docker-node
  pfe_logstash_host: logstash
  spring_profiles_active: prod
