apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: transport.host
              value: localhost
          volumeMounts:
            - name: elasticsearchdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearchdata
          persistentVolumeClaim:
            claimName: elasticsearchdata
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - name: "9200"
      port: 9200
      nodePort: 30001
    - name: "9300"
      port: 9300
      nodePort: 30002
###
