apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-management
          ports:
            - containerPort: 15671
            - containerPort: 15672
            - containerPort: 25672
            - containerPort: 4369
            - containerPort: 4396
            - containerPort: 5671
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: "15671"
      port: 15671
    - name: "15672"
      port: 15672
    - name: "25672"
      port: 25672
    - name: "4369"
      port: 4369
    - name: "4396"
      port: 4396
    - name: "5671"
      port: 5671
    - name: "5672"
      port: 5672
###
