apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: karimsaieh/pfe-search-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3012
          env:
            - name: "FORCE_REDEPLOY" ## https://github.com/kubernetes/kubernetes/issues/33664
              value: "will be chasdhhnged during build doooodjiuerh"
          envFrom:
            - configMapRef:
                name: search-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  type: NodePort
  ports:
    - port: 3012
###
