apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tika
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - name: tika
          image: logicalspark/docker-tikaserver
          ports:
            - containerPort: 9998

---
apiVersion: v1
kind: Service
metadata:
  name: tika
spec:
  selector:
    app: tika
  type: NodePort
  ports:
    - port: 9998
